apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudsqlproxy-metadata
  name: cloudsqlproxy-metadata
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsqlproxy-metadata
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloudsqlproxy-metadata
    spec:
      containers:
      - command:
        - /cloud_sql_proxy
        - -instances=production-205919:us-central1:intellipse-metadata=tcp:0.0.0.0:5432
        - -credential_file=/secrets/cloudsql/credentials.json
        - -quiet
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        imagePullPolicy: IfNotPresent
        name: cloudsql-proxy
        ports:
        - containerPort: 5432
          name: csqlproxyport
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudsqlproxy-metadata
  name: cloudsqlproxy-metadata
  namespace: default
spec:
  ports:
  - name: scsqlproxyport
    port: 5432
    protocol: TCP
    targetPort: csqlproxyport
  selector:
    app: cloudsqlproxy-metadata
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
